/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GetTimezonesResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetTimezonesResponseFromJSON,
    GetTimezonesResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TimezonesApi extends runtime.BaseAPI {

    /**
     * Get a list of timezones and associated timezone keys.
     * Get timezones
     */
    async getTimezonesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTimezonesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("ManagementAPI", ["read:timezones"]);
        }

        const response = await this.request({
            path: `/api/v1/timezones`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTimezonesResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of timezones and associated timezone keys.
     * Get timezones
     */
    async getTimezones(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTimezonesResponse> {
        const response = await this.getTimezonesRaw(initOverrides);
        return await response.value();
    }

}
