/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddAPIsRequest
 */
export interface AddAPIsRequest {
    /**
     * 
     * @type {string}
     * @memberof AddAPIsRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddAPIsRequest
     */
    audience: string;
}

/**
 * Check if a given object implements the AddAPIsRequest interface.
 */
export function instanceOfAddAPIsRequest(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('audience' in value)) return false;
    return true;
}

export function AddAPIsRequestFromJSON(json: any): AddAPIsRequest {
    return AddAPIsRequestFromJSONTyped(json, false);
}

export function AddAPIsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAPIsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'audience': json['audience'],
    };
}

export function AddAPIsRequestToJSON(value?: AddAPIsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'audience': value['audience'],
    };
}

