/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddOrganizationUsersRequestUsersInner } from './AddOrganizationUsersRequestUsersInner';
import {
    AddOrganizationUsersRequestUsersInnerFromJSON,
    AddOrganizationUsersRequestUsersInnerFromJSONTyped,
    AddOrganizationUsersRequestUsersInnerToJSON,
} from './AddOrganizationUsersRequestUsersInner';

/**
 * 
 * @export
 * @interface AddOrganizationUsersRequest
 */
export interface AddOrganizationUsersRequest {
    /**
     * Users to be added to the organization.
     * @type {Array<AddOrganizationUsersRequestUsersInner>}
     * @memberof AddOrganizationUsersRequest
     */
    users?: Array<AddOrganizationUsersRequestUsersInner>;
}

/**
 * Check if a given object implements the AddOrganizationUsersRequest interface.
 */
export function instanceOfAddOrganizationUsersRequest(value: object): value is AddOrganizationUsersRequest {
    return true;
}

export function AddOrganizationUsersRequestFromJSON(json: any): AddOrganizationUsersRequest {
    return AddOrganizationUsersRequestFromJSONTyped(json, false);
}

export function AddOrganizationUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrganizationUsersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(AddOrganizationUsersRequestUsersInnerFromJSON)),
    };
}

export function AddOrganizationUsersRequestToJSON(value?: AddOrganizationUsersRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(AddOrganizationUsersRequestUsersInnerToJSON)),
    };
}

