/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddOrganizationUsersRequestUsersInner
 */
export interface AddOrganizationUsersRequestUsersInner {
    /**
     * The users id.
     * @type {string}
     * @memberof AddOrganizationUsersRequestUsersInner
     */
    id?: string;
    /**
     * Role keys to assign to the user.
     * @type {Array<string>}
     * @memberof AddOrganizationUsersRequestUsersInner
     */
    roles?: Array<string>;
    /**
     * Permission keys to assign to the user.
     * @type {Array<string>}
     * @memberof AddOrganizationUsersRequestUsersInner
     */
    permissions?: Array<string>;
}

/**
 * Check if a given object implements the AddOrganizationUsersRequestUsersInner interface.
 */
export function instanceOfAddOrganizationUsersRequestUsersInner(value: object): value is AddOrganizationUsersRequestUsersInner {
    return true;
}

export function AddOrganizationUsersRequestUsersInnerFromJSON(json: any): AddOrganizationUsersRequestUsersInner {
    return AddOrganizationUsersRequestUsersInnerFromJSONTyped(json, false);
}

export function AddOrganizationUsersRequestUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrganizationUsersRequestUsersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function AddOrganizationUsersRequestUsersInnerToJSON(value?: AddOrganizationUsersRequestUsersInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'roles': value['roles'],
        'permissions': value['permissions'],
    };
}

