/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorizeAppApiResponse
 */
export interface AuthorizeAppApiResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthorizeAppApiResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizeAppApiResponse
     */
    code?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthorizeAppApiResponse
     */
    applicationsDisconnected?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthorizeAppApiResponse
     */
    applicationsConnected?: Array<string>;
}

/**
 * Check if a given object implements the AuthorizeAppApiResponse interface.
 */
export function instanceOfAuthorizeAppApiResponse(value: object): value is AuthorizeAppApiResponse {
    return true;
}

export function AuthorizeAppApiResponseFromJSON(json: any): AuthorizeAppApiResponse {
    return AuthorizeAppApiResponseFromJSONTyped(json, false);
}

export function AuthorizeAppApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizeAppApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'applicationsDisconnected': json['applications_disconnected'] == null ? undefined : json['applications_disconnected'],
        'applicationsConnected': json['applications_connected'] == null ? undefined : json['applications_connected'],
    };
}

  export function AuthorizeAppApiResponseToJSON(json: any): AuthorizeAppApiResponse {
      return AuthorizeAppApiResponseToJSONTyped(json, false);
  }

  export function AuthorizeAppApiResponseToJSONTyped(value?: AuthorizeAppApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'applications_disconnected': value['applicationsDisconnected'],
        'applications_connected': value['applicationsConnected'],
    };
}

