/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectedAppsAccessToken
 */
export interface ConnectedAppsAccessToken {
    /**
     * The access token to access a third-party provider.
     * @type {string}
     * @memberof ConnectedAppsAccessToken
     */
    accessToken?: string;
    /**
     * The date and time that the access token expires.
     * @type {string}
     * @memberof ConnectedAppsAccessToken
     */
    accessTokenExpiry?: string;
}

/**
 * Check if a given object implements the ConnectedAppsAccessToken interface.
 */
export function instanceOfConnectedAppsAccessToken(value: object): boolean {
    return true;
}

export function ConnectedAppsAccessTokenFromJSON(json: any): ConnectedAppsAccessToken {
    return ConnectedAppsAccessTokenFromJSONTyped(json, false);
}

export function ConnectedAppsAccessTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectedAppsAccessToken {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'accessTokenExpiry': json['access_token_expiry'] == null ? undefined : json['access_token_expiry'],
    };
}

export function ConnectedAppsAccessTokenToJSON(value?: ConnectedAppsAccessToken | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access_token': value['accessToken'],
        'access_token_expiry': value['accessTokenExpiry'],
    };
}

