/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateWebhookResponseWebhook } from './CreateWebhookResponseWebhook';
import {
    CreateWebhookResponseWebhookFromJSON,
    CreateWebhookResponseWebhookFromJSONTyped,
    CreateWebhookResponseWebhookToJSON,
} from './CreateWebhookResponseWebhook';

/**
 * 
 * @export
 * @interface CreateWebhookResponse
 */
export interface CreateWebhookResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof CreateWebhookResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof CreateWebhookResponse
     */
    message?: string;
    /**
     * 
     * @type {CreateWebhookResponseWebhook}
     * @memberof CreateWebhookResponse
     */
    webhook?: CreateWebhookResponseWebhook;
}

/**
 * Check if a given object implements the CreateWebhookResponse interface.
 */
export function instanceOfCreateWebhookResponse(value: object): boolean {
    return true;
}

export function CreateWebhookResponseFromJSON(json: any): CreateWebhookResponse {
    return CreateWebhookResponseFromJSONTyped(json, false);
}

export function CreateWebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'webhook': json['webhook'] == null ? undefined : CreateWebhookResponseWebhookFromJSON(json['webhook']),
    };
}

export function CreateWebhookResponseToJSON(value?: CreateWebhookResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'webhook': CreateWebhookResponseWebhookToJSON(value['webhook']),
    };
}

