/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationUserPermissionRequest
 */
export interface CreateOrganizationUserPermissionRequest {
    /**
     * The permission id.
     * @type {string}
     * @memberof CreateOrganizationUserPermissionRequest
     */
    permissionId?: string;
}

/**
 * Check if a given object implements the CreateOrganizationUserPermissionRequest interface.
 */
export function instanceOfCreateOrganizationUserPermissionRequest(value: object): value is CreateOrganizationUserPermissionRequest {
    return true;
}

export function CreateOrganizationUserPermissionRequestFromJSON(json: any): CreateOrganizationUserPermissionRequest {
    return CreateOrganizationUserPermissionRequestFromJSONTyped(json, false);
}

export function CreateOrganizationUserPermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationUserPermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'permissionId': json['permission_id'] == null ? undefined : json['permission_id'],
    };
}

export function CreateOrganizationUserPermissionRequestToJSON(value?: CreateOrganizationUserPermissionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'permission_id': value['permissionId'],
    };
}

