/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebHookRequest
 */
export interface CreateWebHookRequest {
    /**
     * The webhook endpoint url
     * @type {string}
     * @memberof CreateWebHookRequest
     */
    endpoint: string;
    /**
     * Array of event type keys
     * @type {Array<string>}
     * @memberof CreateWebHookRequest
     */
    eventTypes: Array<string>;
    /**
     * The webhook name
     * @type {string}
     * @memberof CreateWebHookRequest
     */
    name: string;
    /**
     * The webhook description
     * @type {string}
     * @memberof CreateWebHookRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateWebHookRequest interface.
 */
export function instanceOfCreateWebHookRequest(value: object): value is CreateWebHookRequest {
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('eventTypes' in value) || value['eventTypes'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateWebHookRequestFromJSON(json: any): CreateWebHookRequest {
    return CreateWebHookRequestFromJSONTyped(json, false);
}

export function CreateWebHookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebHookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'],
        'eventTypes': json['event_types'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateWebHookRequestToJSON(value?: CreateWebHookRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'endpoint': value['endpoint'],
        'event_types': value['eventTypes'],
        'name': value['name'],
        'description': value['description'],
    };
}

