/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePropertyRequest
 */
export interface CreatePropertyRequest {
    /**
     * The name of the property.
     * @type {string}
     * @memberof CreatePropertyRequest
     */
    name: string;
    /**
     * Description of the property purpose.
     * @type {string}
     * @memberof CreatePropertyRequest
     */
    description?: string;
    /**
     * The property identifier to use in code.
     * @type {string}
     * @memberof CreatePropertyRequest
     */
    key: string;
    /**
     * The property type.
     * @type {string}
     * @memberof CreatePropertyRequest
     */
    type: CreatePropertyRequestTypeEnum;
    /**
     * The context that the property applies to.
     * @type {string}
     * @memberof CreatePropertyRequest
     */
    context: CreatePropertyRequestContextEnum;
    /**
     * Whether the property can be included in id and access tokens.
     * @type {boolean}
     * @memberof CreatePropertyRequest
     */
    isPrivate: boolean;
    /**
     * Which category the property belongs to.
     * @type {string}
     * @memberof CreatePropertyRequest
     */
    categoryId: string;
}


/**
 * @export
 */
export const CreatePropertyRequestTypeEnum = {
    SingleLineText: 'single_line_text',
    MultiLineText: 'multi_line_text'
} as const;
export type CreatePropertyRequestTypeEnum = typeof CreatePropertyRequestTypeEnum[keyof typeof CreatePropertyRequestTypeEnum];

/**
 * @export
 */
export const CreatePropertyRequestContextEnum = {
    Org: 'org',
    Usr: 'usr'
} as const;
export type CreatePropertyRequestContextEnum = typeof CreatePropertyRequestContextEnum[keyof typeof CreatePropertyRequestContextEnum];


/**
 * Check if a given object implements the CreatePropertyRequest interface.
 */
export function instanceOfCreatePropertyRequest(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('key' in value)) return false;
    if (!('type' in value)) return false;
    if (!('context' in value)) return false;
    if (!('isPrivate' in value)) return false;
    if (!('categoryId' in value)) return false;
    return true;
}

export function CreatePropertyRequestFromJSON(json: any): CreatePropertyRequest {
    return CreatePropertyRequestFromJSONTyped(json, false);
}

export function CreatePropertyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePropertyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'key': json['key'],
        'type': json['type'],
        'context': json['context'],
        'isPrivate': json['is_private'],
        'categoryId': json['category_id'],
    };
}

export function CreatePropertyRequestToJSON(value?: CreatePropertyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'key': value['key'],
        'type': value['type'],
        'context': value['context'],
        'is_private': value['isPrivate'],
        'category_id': value['categoryId'],
    };
}

