/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Basic information required to create a user.
 * @export
 * @interface CreateUserRequestProfile
 */
export interface CreateUserRequestProfile {
    /**
     * User's first name.
     * @type {string}
     * @memberof CreateUserRequestProfile
     */
    givenName?: string;
    /**
     * User's last name.
     * @type {string}
     * @memberof CreateUserRequestProfile
     */
    familyName?: string;
}

/**
 * Check if a given object implements the CreateUserRequestProfile interface.
 */
export function instanceOfCreateUserRequestProfile(value: object): value is CreateUserRequestProfile {
    return true;
}

export function CreateUserRequestProfileFromJSON(json: any): CreateUserRequestProfile {
    return CreateUserRequestProfileFromJSONTyped(json, false);
}

export function CreateUserRequestProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequestProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
    };
}

export function CreateUserRequestProfileToJSON(value?: CreateUserRequestProfile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'given_name': value['givenName'],
        'family_name': value['familyName'],
    };
}

