/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateApisResponseApi } from './CreateApisResponseApi';
import {
    CreateApisResponseApiFromJSON,
    CreateApisResponseApiFromJSONTyped,
    CreateApisResponseApiToJSON,
} from './CreateApisResponseApi';

/**
 * 
 * @export
 * @interface CreateApisResponse
 */
export interface CreateApisResponse {
    /**
     * A Kinde generated message.
     * @type {string}
     * @memberof CreateApisResponse
     */
    message?: string;
    /**
     * A Kinde generated status code.
     * @type {string}
     * @memberof CreateApisResponse
     */
    code?: string;
    /**
     * 
     * @type {CreateApisResponseApi}
     * @memberof CreateApisResponse
     */
    api?: CreateApisResponseApi;
}

/**
 * Check if a given object implements the CreateApisResponse interface.
 */
export function instanceOfCreateApisResponse(value: object): value is CreateApisResponse {
    return true;
}

export function CreateApisResponseFromJSON(json: any): CreateApisResponse {
    return CreateApisResponseFromJSONTyped(json, false);
}

export function CreateApisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'api': json['api'] == null ? undefined : CreateApisResponseApiFromJSON(json['api']),
    };
}

export function CreateApisResponseToJSON(value?: CreateApisResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'code': value['code'],
        'api': CreateApisResponseApiToJSON(value['api']),
    };
}

