/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateOrganizationResponseOrganization } from './CreateOrganizationResponseOrganization';
import {
    CreateOrganizationResponseOrganizationFromJSON,
    CreateOrganizationResponseOrganizationFromJSONTyped,
    CreateOrganizationResponseOrganizationToJSON,
    CreateOrganizationResponseOrganizationToJSONTyped,
} from './CreateOrganizationResponseOrganization';

/**
 * 
 * @export
 * @interface CreateOrganizationResponse
 */
export interface CreateOrganizationResponse {
    /**
     * Response message.
     * @type {string}
     * @memberof CreateOrganizationResponse
     */
    message?: string;
    /**
     * Response code.
     * @type {string}
     * @memberof CreateOrganizationResponse
     */
    code?: string;
    /**
     * 
     * @type {CreateOrganizationResponseOrganization}
     * @memberof CreateOrganizationResponse
     */
    organization?: CreateOrganizationResponseOrganization;
}

/**
 * Check if a given object implements the CreateOrganizationResponse interface.
 */
export function instanceOfCreateOrganizationResponse(value: object): value is CreateOrganizationResponse {
    return true;
}

export function CreateOrganizationResponseFromJSON(json: any): CreateOrganizationResponse {
    return CreateOrganizationResponseFromJSONTyped(json, false);
}

export function CreateOrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'organization': json['organization'] == null ? undefined : CreateOrganizationResponseOrganizationFromJSON(json['organization']),
    };
}

  export function CreateOrganizationResponseToJSON(json: any): CreateOrganizationResponse {
      return CreateOrganizationResponseToJSONTyped(json, false);
  }

  export function CreateOrganizationResponseToJSONTyped(value?: CreateOrganizationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'organization': CreateOrganizationResponseOrganizationToJSON(value['organization']),
    };
}

