/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateIdentityResponseIdentity } from './CreateIdentityResponseIdentity';
import {
    CreateIdentityResponseIdentityFromJSON,
    CreateIdentityResponseIdentityFromJSONTyped,
    CreateIdentityResponseIdentityToJSON,
} from './CreateIdentityResponseIdentity';

/**
 * 
 * @export
 * @interface CreateIdentityResponse
 */
export interface CreateIdentityResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateIdentityResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateIdentityResponse
     */
    code?: string;
    /**
     * 
     * @type {CreateIdentityResponseIdentity}
     * @memberof CreateIdentityResponse
     */
    identity?: CreateIdentityResponseIdentity;
}

/**
 * Check if a given object implements the CreateIdentityResponse interface.
 */
export function instanceOfCreateIdentityResponse(value: object): value is CreateIdentityResponse {
    return true;
}

export function CreateIdentityResponseFromJSON(json: any): CreateIdentityResponse {
    return CreateIdentityResponseFromJSONTyped(json, false);
}

export function CreateIdentityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIdentityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'identity': json['identity'] == null ? undefined : CreateIdentityResponseIdentityFromJSON(json['identity']),
    };
}

export function CreateIdentityResponseToJSON(value?: CreateIdentityResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'code': value['code'],
        'identity': CreateIdentityResponseIdentityToJSON(value['identity']),
    };
}

