/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCategoryResponseCategory } from './CreateCategoryResponseCategory';
import {
    CreateCategoryResponseCategoryFromJSON,
    CreateCategoryResponseCategoryFromJSONTyped,
    CreateCategoryResponseCategoryToJSON,
    CreateCategoryResponseCategoryToJSONTyped,
} from './CreateCategoryResponseCategory';

/**
 * 
 * @export
 * @interface CreateCategoryResponse
 */
export interface CreateCategoryResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryResponse
     */
    code?: string;
    /**
     * 
     * @type {CreateCategoryResponseCategory}
     * @memberof CreateCategoryResponse
     */
    category?: CreateCategoryResponseCategory;
}

/**
 * Check if a given object implements the CreateCategoryResponse interface.
 */
export function instanceOfCreateCategoryResponse(value: object): value is CreateCategoryResponse {
    return true;
}

export function CreateCategoryResponseFromJSON(json: any): CreateCategoryResponse {
    return CreateCategoryResponseFromJSONTyped(json, false);
}

export function CreateCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'category': json['category'] == null ? undefined : CreateCategoryResponseCategoryFromJSON(json['category']),
    };
}

  export function CreateCategoryResponseToJSON(json: any): CreateCategoryResponse {
      return CreateCategoryResponseToJSONTyped(json, false);
  }

  export function CreateCategoryResponseToJSONTyped(value?: CreateCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'category': CreateCategoryResponseCategoryToJSON(value['category']),
    };
}

