/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCategoryResponseCategory
 */
export interface CreateCategoryResponseCategory {
    /**
     * The category's ID.
     * @type {string}
     * @memberof CreateCategoryResponseCategory
     */
    id?: string;
}

/**
 * Check if a given object implements the CreateCategoryResponseCategory interface.
 */
export function instanceOfCreateCategoryResponseCategory(value: object): value is CreateCategoryResponseCategory {
    return true;
}

export function CreateCategoryResponseCategoryFromJSON(json: any): CreateCategoryResponseCategory {
    return CreateCategoryResponseCategoryFromJSONTyped(json, false);
}

export function CreateCategoryResponseCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryResponseCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateCategoryResponseCategoryToJSON(value?: CreateCategoryResponseCategory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

