/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCategoryRequest
 */
export interface CreateCategoryRequest {
    /**
     * The name of the category.
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    name: string;
    /**
     * The context that the category applies to.
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    context: CreateCategoryRequestContextEnum;
}


/**
 * @export
 */
export const CreateCategoryRequestContextEnum = {
    Org: 'org',
    Usr: 'usr'
} as const;
export type CreateCategoryRequestContextEnum = typeof CreateCategoryRequestContextEnum[keyof typeof CreateCategoryRequestContextEnum];


/**
 * Check if a given object implements the CreateCategoryRequest interface.
 */
export function instanceOfCreateCategoryRequest(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('context' in value)) return false;
    return true;
}

export function CreateCategoryRequestFromJSON(json: any): CreateCategoryRequest {
    return CreateCategoryRequestFromJSONTyped(json, false);
}

export function CreateCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'context': json['context'],
    };
}

export function CreateCategoryRequestToJSON(value?: CreateCategoryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'context': value['context'],
    };
}

