/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateIdentityResponseIdentity
 */
export interface CreateIdentityResponseIdentity {
    /**
     * The identity's ID.
     * @type {string}
     * @memberof CreateIdentityResponseIdentity
     */
    id?: string;
}

/**
 * Check if a given object implements the CreateIdentityResponseIdentity interface.
 */
export function instanceOfCreateIdentityResponseIdentity(value: object): value is CreateIdentityResponseIdentity {
    return true;
}

export function CreateIdentityResponseIdentityFromJSON(json: any): CreateIdentityResponseIdentity {
    return CreateIdentityResponseIdentityFromJSONTyped(json, false);
}

export function CreateIdentityResponseIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIdentityResponseIdentity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateIdentityResponseIdentityToJSON(value?: CreateIdentityResponseIdentity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

