/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateConnectionResponseConnection } from './CreateConnectionResponseConnection';
import {
    CreateConnectionResponseConnectionFromJSON,
    CreateConnectionResponseConnectionFromJSONTyped,
    CreateConnectionResponseConnectionToJSON,
} from './CreateConnectionResponseConnection';

/**
 * 
 * @export
 * @interface CreateConnectionResponse
 */
export interface CreateConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateConnectionResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateConnectionResponse
     */
    code?: string;
    /**
     * 
     * @type {CreateConnectionResponseConnection}
     * @memberof CreateConnectionResponse
     */
    connection?: CreateConnectionResponseConnection;
}

/**
 * Check if a given object implements the CreateConnectionResponse interface.
 */
export function instanceOfCreateConnectionResponse(value: object): boolean {
    return true;
}

export function CreateConnectionResponseFromJSON(json: any): CreateConnectionResponse {
    return CreateConnectionResponseFromJSONTyped(json, false);
}

export function CreateConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'connection': json['connection'] == null ? undefined : CreateConnectionResponseConnectionFromJSON(json['connection']),
    };
}

export function CreateConnectionResponseToJSON(value?: CreateConnectionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'code': value['code'],
        'connection': CreateConnectionResponseConnectionToJSON(value['connection']),
    };
}

