/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteApiResponse
 */
export interface DeleteApiResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteApiResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteApiResponse
     */
    code?: string;
}

/**
 * Check if a given object implements the DeleteApiResponse interface.
 */
export function instanceOfDeleteApiResponse(value: object): value is DeleteApiResponse {
    return true;
}

export function DeleteApiResponseFromJSON(json: any): DeleteApiResponse {
    return DeleteApiResponseFromJSONTyped(json, false);
}

export function DeleteApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function DeleteApiResponseToJSON(value?: DeleteApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'code': value['code'],
    };
}

