/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventType
 */
export interface EventType {
    /**
     * 
     * @type {string}
     * @memberof EventType
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EventType
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof EventType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EventType
     */
    origin?: string;
    /**
     * 
     * @type {object}
     * @memberof EventType
     */
    schema?: object;
}

/**
 * Check if a given object implements the EventType interface.
 */
export function instanceOfEventType(value: object): boolean {
    return true;
}

export function EventTypeFromJSON(json: any): EventType {
    return EventTypeFromJSONTyped(json, false);
}

export function EventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'schema': json['schema'] == null ? undefined : json['schema'],
    };
}

export function EventTypeToJSON(value?: EventType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'origin': value['origin'],
        'schema': value['schema'],
    };
}

