/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetApiResponseApiApplicationsInner } from './GetApiResponseApiApplicationsInner';
import {
    GetApiResponseApiApplicationsInnerFromJSON,
    GetApiResponseApiApplicationsInnerFromJSONTyped,
    GetApiResponseApiApplicationsInnerToJSON,
    GetApiResponseApiApplicationsInnerToJSONTyped,
} from './GetApiResponseApiApplicationsInner';

/**
 * 
 * @export
 * @interface GetApiResponseApi
 */
export interface GetApiResponseApi {
    /**
     * Unique ID of the API.
     * @type {string}
     * @memberof GetApiResponseApi
     */
    id?: string;
    /**
     * The API’s name.
     * @type {string}
     * @memberof GetApiResponseApi
     */
    name?: string;
    /**
     * A unique identifier for the API - commonly the URL. This value will be used as the `audience` parameter in authorization claims.
     * @type {string}
     * @memberof GetApiResponseApi
     */
    audience?: string;
    /**
     * Whether or not it is the Kinde management API.
     * @type {boolean}
     * @memberof GetApiResponseApi
     */
    isManagementApi?: boolean;
    /**
     * 
     * @type {Array<GetApiResponseApiApplicationsInner>}
     * @memberof GetApiResponseApi
     */
    applications?: Array<GetApiResponseApiApplicationsInner>;
}

/**
 * Check if a given object implements the GetApiResponseApi interface.
 */
export function instanceOfGetApiResponseApi(value: object): value is GetApiResponseApi {
    return true;
}

export function GetApiResponseApiFromJSON(json: any): GetApiResponseApi {
    return GetApiResponseApiFromJSONTyped(json, false);
}

export function GetApiResponseApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiResponseApi {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'audience': json['audience'] == null ? undefined : json['audience'],
        'isManagementApi': json['is_management_api'] == null ? undefined : json['is_management_api'],
        'applications': json['applications'] == null ? undefined : ((json['applications'] as Array<any>).map(GetApiResponseApiApplicationsInnerFromJSON)),
    };
}

  export function GetApiResponseApiToJSON(json: any): GetApiResponseApi {
      return GetApiResponseApiToJSONTyped(json, false);
  }

  export function GetApiResponseApiToJSONTyped(value?: GetApiResponseApi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'audience': value['audience'],
        'is_management_api': value['isManagementApi'],
        'applications': value['applications'] == null ? undefined : ((value['applications'] as Array<any>).map(GetApiResponseApiApplicationsInnerToJSON)),
    };
}

