/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Applications } from './Applications';
import {
    ApplicationsFromJSON,
    ApplicationsFromJSONTyped,
    ApplicationsToJSON,
} from './Applications';

/**
 * 
 * @export
 * @interface GetApplicationsResponse
 */
export interface GetApplicationsResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetApplicationsResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetApplicationsResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<Applications>}
     * @memberof GetApplicationsResponse
     */
    applications?: Array<Applications>;
    /**
     * Pagination token.
     * @type {string}
     * @memberof GetApplicationsResponse
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the GetApplicationsResponse interface.
 */
export function instanceOfGetApplicationsResponse(value: object): value is GetApplicationsResponse {
    return true;
}

export function GetApplicationsResponseFromJSON(json: any): GetApplicationsResponse {
    return GetApplicationsResponseFromJSONTyped(json, false);
}

export function GetApplicationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApplicationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'applications': json['applications'] == null ? undefined : ((json['applications'] as Array<any>).map(ApplicationsFromJSON)),
        'nextToken': json['next_token'] == null ? undefined : json['next_token'],
    };
}

export function GetApplicationsResponseToJSON(value?: GetApplicationsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'applications': value['applications'] == null ? undefined : ((value['applications'] as Array<any>).map(ApplicationsToJSON)),
        'next_token': value['nextToken'],
    };
}

