/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApplicationResponseApplication
 */
export interface GetApplicationResponseApplication {
    /**
     * The application's identifier.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    id?: string;
    /**
     * The application's name.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    name?: string;
    /**
     * The application's type.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    type?: string;
    /**
     * The application's client id.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    clientId?: string;
    /**
     * The application's client secret.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    clientSecret?: string;
    /**
     * The default login route for resolving session issues.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    loginUri?: string;
    /**
     * The homepage link to your application.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    homepageUri?: string;
}

/**
 * Check if a given object implements the GetApplicationResponseApplication interface.
 */
export function instanceOfGetApplicationResponseApplication(value: object): value is GetApplicationResponseApplication {
    return true;
}

export function GetApplicationResponseApplicationFromJSON(json: any): GetApplicationResponseApplication {
    return GetApplicationResponseApplicationFromJSONTyped(json, false);
}

export function GetApplicationResponseApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApplicationResponseApplication {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
        'loginUri': json['login_uri'] == null ? undefined : json['login_uri'],
        'homepageUri': json['homepage_uri'] == null ? undefined : json['homepage_uri'],
    };
}

export function GetApplicationResponseApplicationToJSON(value?: GetApplicationResponseApplication | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'login_uri': value['loginUri'],
        'homepage_uri': value['homepageUri'],
    };
}

