/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiResponseApiApplicationsInner
 */
export interface GetApiResponseApiApplicationsInner {
    /**
     * The Client ID of the application.
     * @type {string}
     * @memberof GetApiResponseApiApplicationsInner
     */
    id?: string;
    /**
     * The application's name.
     * @type {string}
     * @memberof GetApiResponseApiApplicationsInner
     */
    name?: string;
    /**
     * The application's type.
     * @type {string}
     * @memberof GetApiResponseApiApplicationsInner
     */
    type?: GetApiResponseApiApplicationsInnerTypeEnum;
    /**
     * Whether or not the application is authorized to access the API
     * @type {boolean}
     * @memberof GetApiResponseApiApplicationsInner
     */
    isActive?: boolean | null;
}


/**
 * @export
 */
export const GetApiResponseApiApplicationsInnerTypeEnum = {
    MachineToMachineM2M: 'Machine to machine (M2M)',
    BackEndWeb: 'Back-end web',
    FrontEndAndMobile: 'Front-end and mobile'
} as const;
export type GetApiResponseApiApplicationsInnerTypeEnum = typeof GetApiResponseApiApplicationsInnerTypeEnum[keyof typeof GetApiResponseApiApplicationsInnerTypeEnum];


/**
 * Check if a given object implements the GetApiResponseApiApplicationsInner interface.
 */
export function instanceOfGetApiResponseApiApplicationsInner(value: object): value is GetApiResponseApiApplicationsInner {
    return true;
}

export function GetApiResponseApiApplicationsInnerFromJSON(json: any): GetApiResponseApiApplicationsInner {
    return GetApiResponseApiApplicationsInnerFromJSONTyped(json, false);
}

export function GetApiResponseApiApplicationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiResponseApiApplicationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function GetApiResponseApiApplicationsInnerToJSON(value?: GetApiResponseApiApplicationsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'is_active': value['isActive'],
    };
}

