/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApisResponseApisInner
 */
export interface GetApisResponseApisInner {
    /**
     * The unique ID for the API.
     * @type {string}
     * @memberof GetApisResponseApisInner
     */
    id?: string;
    /**
     * The API’s name.
     * @type {string}
     * @memberof GetApisResponseApisInner
     */
    name?: string;
    /**
     * A unique identifier for the API - commonly the URL. This value will be used as the `audience` parameter in authorization claims.
     * @type {string}
     * @memberof GetApisResponseApisInner
     */
    audience?: string;
    /**
     * Whether or not it is the Kinde management API.
     * @type {boolean}
     * @memberof GetApisResponseApisInner
     */
    isManagementApi?: boolean;
}

/**
 * Check if a given object implements the GetApisResponseApisInner interface.
 */
export function instanceOfGetApisResponseApisInner(value: object): value is GetApisResponseApisInner {
    return true;
}

export function GetApisResponseApisInnerFromJSON(json: any): GetApisResponseApisInner {
    return GetApisResponseApisInnerFromJSONTyped(json, false);
}

export function GetApisResponseApisInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApisResponseApisInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'audience': json['audience'] == null ? undefined : json['audience'],
        'isManagementApi': json['is_management_api'] == null ? undefined : json['is_management_api'],
    };
}

export function GetApisResponseApisInnerToJSON(value?: GetApisResponseApisInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'audience': value['audience'],
        'is_management_api': value['isManagementApi'],
    };
}

