/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface GetCategoriesResponse
 */
export interface GetCategoriesResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetCategoriesResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetCategoriesResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<Category>}
     * @memberof GetCategoriesResponse
     */
    categories?: Array<Category>;
    /**
     * Whether more records exist.
     * @type {boolean}
     * @memberof GetCategoriesResponse
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the GetCategoriesResponse interface.
 */
export function instanceOfGetCategoriesResponse(value: object): boolean {
    return true;
}

export function GetCategoriesResponseFromJSON(json: any): GetCategoriesResponse {
    return GetCategoriesResponseFromJSONTyped(json, false);
}

export function GetCategoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCategoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
    };
}

export function GetCategoriesResponseToJSON(value?: GetCategoriesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryToJSON)),
        'has_more': value['hasMore'],
    };
}

