/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEventResponseEvent } from './GetEventResponseEvent';
import {
    GetEventResponseEventFromJSON,
    GetEventResponseEventFromJSONTyped,
    GetEventResponseEventToJSON,
    GetEventResponseEventToJSONTyped,
} from './GetEventResponseEvent';

/**
 * 
 * @export
 * @interface GetEventResponse
 */
export interface GetEventResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetEventResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetEventResponse
     */
    message?: string;
    /**
     * 
     * @type {GetEventResponseEvent}
     * @memberof GetEventResponse
     */
    event?: GetEventResponseEvent;
}

/**
 * Check if a given object implements the GetEventResponse interface.
 */
export function instanceOfGetEventResponse(value: object): value is GetEventResponse {
    return true;
}

export function GetEventResponseFromJSON(json: any): GetEventResponse {
    return GetEventResponseFromJSONTyped(json, false);
}

export function GetEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'event': json['event'] == null ? undefined : GetEventResponseEventFromJSON(json['event']),
    };
}

  export function GetEventResponseToJSON(json: any): GetEventResponse {
      return GetEventResponseToJSONTyped(json, false);
  }

  export function GetEventResponseToJSONTyped(value?: GetEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'event': GetEventResponseEventToJSON(value['event']),
    };
}

