/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
} from './Identity';

/**
 * 
 * @export
 * @interface GetIdentitiesResponse
 */
export interface GetIdentitiesResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetIdentitiesResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetIdentitiesResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<Identity>}
     * @memberof GetIdentitiesResponse
     */
    properties?: Array<Identity>;
    /**
     * Whether more records exist.
     * @type {boolean}
     * @memberof GetIdentitiesResponse
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the GetIdentitiesResponse interface.
 */
export function instanceOfGetIdentitiesResponse(value: object): value is GetIdentitiesResponse {
    return true;
}

export function GetIdentitiesResponseFromJSON(json: any): GetIdentitiesResponse {
    return GetIdentitiesResponseFromJSONTyped(json, false);
}

export function GetIdentitiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIdentitiesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'properties': json['properties'] == null ? undefined : ((json['properties'] as Array<any>).map(IdentityFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
    };
}

export function GetIdentitiesResponseToJSON(value?: GetIdentitiesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'properties': value['properties'] == null ? undefined : ((value['properties'] as Array<any>).map(IdentityToJSON)),
        'has_more': value['hasMore'],
    };
}

