/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetIndustriesResponseIndustriesInner } from './GetIndustriesResponseIndustriesInner';
import {
    GetIndustriesResponseIndustriesInnerFromJSON,
    GetIndustriesResponseIndustriesInnerFromJSONTyped,
    GetIndustriesResponseIndustriesInnerToJSON,
    GetIndustriesResponseIndustriesInnerToJSONTyped,
} from './GetIndustriesResponseIndustriesInner';

/**
 * 
 * @export
 * @interface GetIndustriesResponse
 */
export interface GetIndustriesResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetIndustriesResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetIndustriesResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<GetIndustriesResponseIndustriesInner>}
     * @memberof GetIndustriesResponse
     */
    industries?: Array<GetIndustriesResponseIndustriesInner>;
}

/**
 * Check if a given object implements the GetIndustriesResponse interface.
 */
export function instanceOfGetIndustriesResponse(value: object): value is GetIndustriesResponse {
    return true;
}

export function GetIndustriesResponseFromJSON(json: any): GetIndustriesResponse {
    return GetIndustriesResponseFromJSONTyped(json, false);
}

export function GetIndustriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIndustriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'industries': json['industries'] == null ? undefined : ((json['industries'] as Array<any>).map(GetIndustriesResponseIndustriesInnerFromJSON)),
    };
}

  export function GetIndustriesResponseToJSON(json: any): GetIndustriesResponse {
      return GetIndustriesResponseToJSONTyped(json, false);
  }

  export function GetIndustriesResponseToJSONTyped(value?: GetIndustriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'industries': value['industries'] == null ? undefined : ((value['industries'] as Array<any>).map(GetIndustriesResponseIndustriesInnerToJSON)),
    };
}

