/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetIndustriesResponseIndustriesInner
 */
export interface GetIndustriesResponseIndustriesInner {
    /**
     * The unique key for the industry.
     * @type {string}
     * @memberof GetIndustriesResponseIndustriesInner
     */
    key?: string;
    /**
     * The display name for the industry.
     * @type {string}
     * @memberof GetIndustriesResponseIndustriesInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetIndustriesResponseIndustriesInner interface.
 */
export function instanceOfGetIndustriesResponseIndustriesInner(value: object): value is GetIndustriesResponseIndustriesInner {
    return true;
}

export function GetIndustriesResponseIndustriesInnerFromJSON(json: any): GetIndustriesResponseIndustriesInner {
    return GetIndustriesResponseIndustriesInnerFromJSONTyped(json, false);
}

export function GetIndustriesResponseIndustriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIndustriesResponseIndustriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

  export function GetIndustriesResponseIndustriesInnerToJSON(json: any): GetIndustriesResponseIndustriesInner {
      return GetIndustriesResponseIndustriesInnerToJSONTyped(json, false);
  }

  export function GetIndustriesResponseIndustriesInnerToJSONTyped(value?: GetIndustriesResponseIndustriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'name': value['name'],
    };
}

