/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Property } from './Property';
import {
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
} from './Property';

/**
 * 
 * @export
 * @interface GetPropertiesResponse
 */
export interface GetPropertiesResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetPropertiesResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetPropertiesResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<Property>}
     * @memberof GetPropertiesResponse
     */
    properties?: Array<Property>;
    /**
     * Whether more records exist.
     * @type {boolean}
     * @memberof GetPropertiesResponse
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the GetPropertiesResponse interface.
 */
export function instanceOfGetPropertiesResponse(value: object): boolean {
    return true;
}

export function GetPropertiesResponseFromJSON(json: any): GetPropertiesResponse {
    return GetPropertiesResponseFromJSONTyped(json, false);
}

export function GetPropertiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPropertiesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'properties': json['properties'] == null ? undefined : ((json['properties'] as Array<any>).map(PropertyFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
    };
}

export function GetPropertiesResponseToJSON(value?: GetPropertiesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'properties': value['properties'] == null ? undefined : ((value['properties'] as Array<any>).map(PropertyToJSON)),
        'has_more': value['hasMore'],
    };
}

