/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscribersSubscriber } from './SubscribersSubscriber';
import {
    SubscribersSubscriberFromJSON,
    SubscribersSubscriberFromJSONTyped,
    SubscribersSubscriberToJSON,
} from './SubscribersSubscriber';

/**
 * 
 * @export
 * @interface GetSubscribersResponse
 */
export interface GetSubscribersResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetSubscribersResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetSubscribersResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<SubscribersSubscriber>}
     * @memberof GetSubscribersResponse
     */
    subscribers?: Array<SubscribersSubscriber>;
    /**
     * Pagination token.
     * @type {string}
     * @memberof GetSubscribersResponse
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the GetSubscribersResponse interface.
 */
export function instanceOfGetSubscribersResponse(value: object): value is GetSubscribersResponse {
    return true;
}

export function GetSubscribersResponseFromJSON(json: any): GetSubscribersResponse {
    return GetSubscribersResponseFromJSONTyped(json, false);
}

export function GetSubscribersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscribersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'subscribers': json['subscribers'] == null ? undefined : ((json['subscribers'] as Array<any>).map(SubscribersSubscriberFromJSON)),
        'nextToken': json['next_token'] == null ? undefined : json['next_token'],
    };
}

export function GetSubscribersResponseToJSON(value?: GetSubscribersResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'subscribers': value['subscribers'] == null ? undefined : ((value['subscribers'] as Array<any>).map(SubscribersSubscriberToJSON)),
        'next_token': value['nextToken'],
    };
}

