/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTimezonesResponseTimezonesInner
 */
export interface GetTimezonesResponseTimezonesInner {
    /**
     * The unique key for the timezone.
     * @type {string}
     * @memberof GetTimezonesResponseTimezonesInner
     */
    key?: string;
    /**
     * The display name for the timezone.
     * @type {string}
     * @memberof GetTimezonesResponseTimezonesInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetTimezonesResponseTimezonesInner interface.
 */
export function instanceOfGetTimezonesResponseTimezonesInner(value: object): value is GetTimezonesResponseTimezonesInner {
    return true;
}

export function GetTimezonesResponseTimezonesInnerFromJSON(json: any): GetTimezonesResponseTimezonesInner {
    return GetTimezonesResponseTimezonesInnerFromJSONTyped(json, false);
}

export function GetTimezonesResponseTimezonesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimezonesResponseTimezonesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

  export function GetTimezonesResponseTimezonesInnerToJSON(json: any): GetTimezonesResponseTimezonesInner {
      return GetTimezonesResponseTimezonesInnerToJSONTyped(json, false);
  }

  export function GetTimezonesResponseTimezonesInnerToJSONTyped(value?: GetTimezonesResponseTimezonesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'name': value['name'],
    };
}

