/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Webhook } from './Webhook';
import {
    WebhookFromJSON,
    WebhookFromJSONTyped,
    WebhookToJSON,
} from './Webhook';

/**
 * 
 * @export
 * @interface GetWebhooksResponse
 */
export interface GetWebhooksResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetWebhooksResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetWebhooksResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<Webhook>}
     * @memberof GetWebhooksResponse
     */
    webhooks?: Array<Webhook>;
}

/**
 * Check if a given object implements the GetWebhooksResponse interface.
 */
export function instanceOfGetWebhooksResponse(value: object): value is GetWebhooksResponse {
    return true;
}

export function GetWebhooksResponseFromJSON(json: any): GetWebhooksResponse {
    return GetWebhooksResponseFromJSONTyped(json, false);
}

export function GetWebhooksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebhooksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'webhooks': json['webhooks'] == null ? undefined : ((json['webhooks'] as Array<any>).map(WebhookFromJSON)),
    };
}

export function GetWebhooksResponseToJSON(value?: GetWebhooksResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'webhooks': value['webhooks'] == null ? undefined : ((value['webhooks'] as Array<any>).map(WebhookToJSON)),
    };
}

