/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Identity
 */
export interface Identity {
    /**
     * 
     * @type {string}
     * @memberof Identity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Identity
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Identity
     */
    isConfirmed?: boolean;
    /**
     * Date of user creation in ISO 8601 format.
     * @type {string}
     * @memberof Identity
     */
    createdOn?: string;
    /**
     * Date of user creation in ISO 8601 format.
     * @type {string}
     * @memberof Identity
     */
    lastLoginOn?: string;
    /**
     * 
     * @type {number}
     * @memberof Identity
     */
    totalLogins?: number;
    /**
     * 
     * @type {string}
     * @memberof Identity
     */
    name?: string;
}

/**
 * Check if a given object implements the Identity interface.
 */
export function instanceOfIdentity(value: object): value is Identity {
    return true;
}

export function IdentityFromJSON(json: any): Identity {
    return IdentityFromJSONTyped(json, false);
}

export function IdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Identity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'isConfirmed': json['is_confirmed'] == null ? undefined : json['is_confirmed'],
        'createdOn': json['created_on'] == null ? undefined : json['created_on'],
        'lastLoginOn': json['last_login_on'] == null ? undefined : json['last_login_on'],
        'totalLogins': json['total_logins'] == null ? undefined : json['total_logins'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

  export function IdentityToJSON(json: any): Identity {
      return IdentityToJSONTyped(json, false);
  }

  export function IdentityToJSONTyped(value?: Identity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'is_confirmed': value['isConfirmed'],
        'created_on': value['createdOn'],
        'last_login_on': value['lastLoginOn'],
        'total_logins': value['totalLogins'],
        'name': value['name'],
    };
}

