/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotFoundResponseErrors } from './NotFoundResponseErrors';
import {
    NotFoundResponseErrorsFromJSON,
    NotFoundResponseErrorsFromJSONTyped,
    NotFoundResponseErrorsToJSON,
    NotFoundResponseErrorsToJSONTyped,
} from './NotFoundResponseErrors';

/**
 * 
 * @export
 * @interface NotFoundResponse
 */
export interface NotFoundResponse {
    /**
     * 
     * @type {NotFoundResponseErrors}
     * @memberof NotFoundResponse
     */
    errors?: NotFoundResponseErrors;
}

/**
 * Check if a given object implements the NotFoundResponse interface.
 */
export function instanceOfNotFoundResponse(value: object): value is NotFoundResponse {
    return true;
}

export function NotFoundResponseFromJSON(json: any): NotFoundResponse {
    return NotFoundResponseFromJSONTyped(json, false);
}

export function NotFoundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : NotFoundResponseErrorsFromJSON(json['errors']),
    };
}

  export function NotFoundResponseToJSON(json: any): NotFoundResponse {
      return NotFoundResponseToJSONTyped(json, false);
  }

  export function NotFoundResponseToJSONTyped(value?: NotFoundResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': NotFoundResponseErrorsToJSON(value['errors']),
    };
}

