/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotFoundResponseErrors
 */
export interface NotFoundResponseErrors {
    /**
     * 
     * @type {string}
     * @memberof NotFoundResponseErrors
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof NotFoundResponseErrors
     */
    message?: string;
}

/**
 * Check if a given object implements the NotFoundResponseErrors interface.
 */
export function instanceOfNotFoundResponseErrors(value: object): value is NotFoundResponseErrors {
    return true;
}

export function NotFoundResponseErrorsFromJSON(json: any): NotFoundResponseErrors {
    return NotFoundResponseErrorsFromJSONTyped(json, false);
}

export function NotFoundResponseErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundResponseErrors {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

  export function NotFoundResponseErrorsToJSON(json: any): NotFoundResponseErrors {
      return NotFoundResponseErrorsToJSONTyped(json, false);
  }

  export function NotFoundResponseErrorsToJSONTyped(value?: NotFoundResponseErrors | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

