/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUserRolePermissionsPermissions
 */
export interface OrganizationUserRolePermissionsPermissions {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRolePermissionsPermissions
     */
    key?: string;
}

/**
 * Check if a given object implements the OrganizationUserRolePermissionsPermissions interface.
 */
export function instanceOfOrganizationUserRolePermissionsPermissions(value: object): value is OrganizationUserRolePermissionsPermissions {
    return true;
}

export function OrganizationUserRolePermissionsPermissionsFromJSON(json: any): OrganizationUserRolePermissionsPermissions {
    return OrganizationUserRolePermissionsPermissionsFromJSONTyped(json, false);
}

export function OrganizationUserRolePermissionsPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserRolePermissionsPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function OrganizationUserRolePermissionsPermissionsToJSON(value?: OrganizationUserRolePermissionsPermissions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
    };
}

