/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationUserRolePermissionsPermissions } from './OrganizationUserRolePermissionsPermissions';
import {
    OrganizationUserRolePermissionsPermissionsFromJSON,
    OrganizationUserRolePermissionsPermissionsFromJSONTyped,
    OrganizationUserRolePermissionsPermissionsToJSON,
} from './OrganizationUserRolePermissionsPermissions';

/**
 * 
 * @export
 * @interface OrganizationUserRolePermissions
 */
export interface OrganizationUserRolePermissions {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRolePermissions
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRolePermissions
     */
    role?: string;
    /**
     * 
     * @type {OrganizationUserRolePermissionsPermissions}
     * @memberof OrganizationUserRolePermissions
     */
    permissions?: OrganizationUserRolePermissionsPermissions;
}

/**
 * Check if a given object implements the OrganizationUserRolePermissions interface.
 */
export function instanceOfOrganizationUserRolePermissions(value: object): boolean {
    return true;
}

export function OrganizationUserRolePermissionsFromJSON(json: any): OrganizationUserRolePermissions {
    return OrganizationUserRolePermissionsFromJSONTyped(json, false);
}

export function OrganizationUserRolePermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserRolePermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'permissions': json['permissions'] == null ? undefined : OrganizationUserRolePermissionsPermissionsFromJSON(json['permissions']),
    };
}

export function OrganizationUserRolePermissionsToJSON(value?: OrganizationUserRolePermissions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'role': value['role'],
        'permissions': OrganizationUserRolePermissionsPermissionsToJSON(value['permissions']),
    };
}

