/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Organization
     */
    isDefault?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    linkColor?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    buttonColor?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    backgroundColor?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    buttonTextColor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Organization
     */
    isAllowRegistrations?: boolean;
}

/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): value is Organization {
    return true;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'linkColor': json['link_color'] == null ? undefined : json['link_color'],
        'buttonColor': json['button_color'] == null ? undefined : json['button_color'],
        'backgroundColor': json['background_color'] == null ? undefined : json['background_color'],
        'buttonTextColor': json['button_text_color'] == null ? undefined : json['button_text_color'],
        'isAllowRegistrations': json['is_allow_registrations'] == null ? undefined : json['is_allow_registrations'],
    };
}

export function OrganizationToJSON(value?: Organization | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'name': value['name'],
        'is_default': value['isDefault'],
        'external_id': value['externalId'],
        'logo': value['logo'],
        'link_color': value['linkColor'],
        'button_color': value['buttonColor'],
        'background_color': value['backgroundColor'],
        'button_text_color': value['buttonTextColor'],
        'is_allow_registrations': value['isAllowRegistrations'],
    };
}

