/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUserRole
 */
export interface OrganizationUserRole {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRole
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRole
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRole
     */
    name?: string;
}

/**
 * Check if a given object implements the OrganizationUserRole interface.
 */
export function instanceOfOrganizationUserRole(value: object): value is OrganizationUserRole {
    return true;
}

export function OrganizationUserRoleFromJSON(json: any): OrganizationUserRole {
    return OrganizationUserRoleFromJSONTyped(json, false);
}

export function OrganizationUserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserRole {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OrganizationUserRoleToJSON(value?: OrganizationUserRole | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'key': value['key'],
        'name': value['name'],
    };
}

