/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUser
 */
export interface OrganizationUser {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    picture?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganizationUser
     */
    roles?: Array<string>;
}

/**
 * Check if a given object implements the OrganizationUser interface.
 */
export function instanceOfOrganizationUser(value: object): boolean {
    return true;
}

export function OrganizationUserFromJSON(json: any): OrganizationUser {
    return OrganizationUserFromJSONTyped(json, false);
}

export function OrganizationUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'picture': json['picture'] == null ? undefined : json['picture'],
        'roles': json['roles'] == null ? undefined : json['roles'],
    };
}

export function OrganizationUserToJSON(value?: OrganizationUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
        'full_name': value['fullName'],
        'last_name': value['lastName'],
        'first_name': value['firstName'],
        'picture': value['picture'],
        'roles': value['roles'],
    };
}

