/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Permissions
 */
export interface Permissions {
    /**
     * The permission's id.
     * @type {string}
     * @memberof Permissions
     */
    id?: string;
    /**
     * The permission identifier to use in code.
     * @type {string}
     * @memberof Permissions
     */
    key?: string;
    /**
     * The permission's name.
     * @type {string}
     * @memberof Permissions
     */
    name?: string;
    /**
     * The permission's description.
     * @type {string}
     * @memberof Permissions
     */
    description?: string;
}

/**
 * Check if a given object implements the Permissions interface.
 */
export function instanceOfPermissions(value: object): value is Permissions {
    return true;
}

export function PermissionsFromJSON(json: any): Permissions {
    return PermissionsFromJSONTyped(json, false);
}

export function PermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Permissions {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

  export function PermissionsToJSON(json: any): Permissions {
      return PermissionsToJSONTyped(json, false);
  }

  export function PermissionsToJSONTyped(value?: Permissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'name': value['name'],
        'description': value['description'],
    };
}

