/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyValue
 */
export interface PropertyValue {
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyValue
     */
    value?: string;
}

/**
 * Check if a given object implements the PropertyValue interface.
 */
export function instanceOfPropertyValue(value: object): boolean {
    return true;
}

export function PropertyValueFromJSON(json: any): PropertyValue {
    return PropertyValueFromJSONTyped(json, false);
}

export function PropertyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function PropertyValueToJSON(value?: PropertyValue | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'key': value['key'],
        'value': value['value'],
    };
}

