/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Roles
 */
export interface Roles {
    /**
     * The role's id.
     * @type {string}
     * @memberof Roles
     */
    id?: string;
    /**
     * The role identifier to use in code.
     * @type {string}
     * @memberof Roles
     */
    key?: string;
    /**
     * The role's name.
     * @type {string}
     * @memberof Roles
     */
    name?: string;
    /**
     * The role's description.
     * @type {string}
     * @memberof Roles
     */
    description?: string;
}

/**
 * Check if a given object implements the Roles interface.
 */
export function instanceOfRoles(value: object): value is Roles {
    return true;
}

export function RolesFromJSON(json: any): Roles {
    return RolesFromJSONTyped(json, false);
}

export function RolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Roles {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

  export function RolesToJSON(json: any): Roles {
      return RolesToJSONTyped(json, false);
  }

  export function RolesToJSONTyped(value?: Roles | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'name': value['name'],
        'description': value['description'],
    };
}

