/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RolesPermissionResponseInner
 */
export interface RolesPermissionResponseInner {
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    description?: string;
}

/**
 * Check if a given object implements the RolesPermissionResponseInner interface.
 */
export function instanceOfRolesPermissionResponseInner(value: object): value is RolesPermissionResponseInner {
    return true;
}

export function RolesPermissionResponseInnerFromJSON(json: any): RolesPermissionResponseInner {
    return RolesPermissionResponseInnerFromJSONTyped(json, false);
}

export function RolesPermissionResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolesPermissionResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

  export function RolesPermissionResponseInnerToJSON(json: any): RolesPermissionResponseInner {
      return RolesPermissionResponseInnerToJSONTyped(json, false);
  }

  export function RolesPermissionResponseInnerToJSONTyped(value?: RolesPermissionResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'name': value['name'],
        'description': value['description'],
    };
}

