/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subscriber
 */
export interface Subscriber {
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    preferredEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    lastName?: string;
}

/**
 * Check if a given object implements the Subscriber interface.
 */
export function instanceOfSubscriber(value: object): boolean {
    return true;
}

export function SubscriberFromJSON(json: any): Subscriber {
    return SubscriberFromJSONTyped(json, false);
}

export function SubscriberFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscriber {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'preferredEmail': json['preferred_email'] == null ? undefined : json['preferred_email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
    };
}

export function SubscriberToJSON(value?: Subscriber | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'preferred_email': value['preferredEmail'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

