/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenErrorResponse
 */
export interface TokenErrorResponse {
    /**
     * Error.
     * @type {string}
     * @memberof TokenErrorResponse
     */
    error?: string;
    /**
     * The error description.
     * @type {string}
     * @memberof TokenErrorResponse
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the TokenErrorResponse interface.
 */
export function instanceOfTokenErrorResponse(value: object): value is TokenErrorResponse {
    return true;
}

export function TokenErrorResponseFromJSON(json: any): TokenErrorResponse {
    return TokenErrorResponseFromJSONTyped(json, false);
}

export function TokenErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

  export function TokenErrorResponseToJSON(json: any): TokenErrorResponse {
      return TokenErrorResponseToJSONTyped(json, false);
  }

  export function TokenErrorResponseToJSONTyped(value?: TokenErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

