/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePropertyRequest
 */
export interface UpdatePropertyRequest {
    /**
     * The name of the property.
     * @type {string}
     * @memberof UpdatePropertyRequest
     */
    name?: string;
    /**
     * Description of the property purpose.
     * @type {string}
     * @memberof UpdatePropertyRequest
     */
    description?: string;
    /**
     * Whether the property can be included in id and access tokens.
     * @type {boolean}
     * @memberof UpdatePropertyRequest
     */
    isPrivate?: boolean;
}

/**
 * Check if a given object implements the UpdatePropertyRequest interface.
 */
export function instanceOfUpdatePropertyRequest(value: object): boolean {
    return true;
}

export function UpdatePropertyRequestFromJSON(json: any): UpdatePropertyRequest {
    return UpdatePropertyRequestFromJSONTyped(json, false);
}

export function UpdatePropertyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePropertyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPrivate': json['is_private'] == null ? undefined : json['is_private'],
    };
}

export function UpdatePropertyRequestToJSON(value?: UpdatePropertyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'is_private': value['isPrivate'],
    };
}

