/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrganizationPropertiesRequest
 */
export interface UpdateOrganizationPropertiesRequest {
    /**
     * Property keys and values
     * @type {object}
     * @memberof UpdateOrganizationPropertiesRequest
     */
    properties: object;
}

/**
 * Check if a given object implements the UpdateOrganizationPropertiesRequest interface.
 */
export function instanceOfUpdateOrganizationPropertiesRequest(value: object): boolean {
    if (!('properties' in value)) return false;
    return true;
}

export function UpdateOrganizationPropertiesRequestFromJSON(json: any): UpdateOrganizationPropertiesRequest {
    return UpdateOrganizationPropertiesRequestFromJSONTyped(json, false);
}

export function UpdateOrganizationPropertiesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationPropertiesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': json['properties'],
    };
}

export function UpdateOrganizationPropertiesRequestToJSON(value?: UpdateOrganizationPropertiesRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'properties': value['properties'],
    };
}

