/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAPIApplicationsRequestApplicationsInner
 */
export interface UpdateAPIApplicationsRequestApplicationsInner {
    /**
     * The application's id.
     * @type {string}
     * @memberof UpdateAPIApplicationsRequestApplicationsInner
     */
    id: string;
    /**
     * Optional operation, set to 'delete' to remove the user from the organization.
     * @type {string}
     * @memberof UpdateAPIApplicationsRequestApplicationsInner
     */
    operation?: string;
}

/**
 * Check if a given object implements the UpdateAPIApplicationsRequestApplicationsInner interface.
 */
export function instanceOfUpdateAPIApplicationsRequestApplicationsInner(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function UpdateAPIApplicationsRequestApplicationsInnerFromJSON(json: any): UpdateAPIApplicationsRequestApplicationsInner {
    return UpdateAPIApplicationsRequestApplicationsInnerFromJSONTyped(json, false);
}

export function UpdateAPIApplicationsRequestApplicationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAPIApplicationsRequestApplicationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'operation': json['operation'] == null ? undefined : json['operation'],
    };
}

export function UpdateAPIApplicationsRequestApplicationsInnerToJSON(value?: UpdateAPIApplicationsRequestApplicationsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'operation': value['operation'],
    };
}

