/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWebhookResponseWebhook
 */
export interface UpdateWebhookResponseWebhook {
    /**
     * 
     * @type {string}
     * @memberof UpdateWebhookResponseWebhook
     */
    id?: string;
}

/**
 * Check if a given object implements the UpdateWebhookResponseWebhook interface.
 */
export function instanceOfUpdateWebhookResponseWebhook(value: object): value is UpdateWebhookResponseWebhook {
    return true;
}

export function UpdateWebhookResponseWebhookFromJSON(json: any): UpdateWebhookResponseWebhook {
    return UpdateWebhookResponseWebhookFromJSONTyped(json, false);
}

export function UpdateWebhookResponseWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebhookResponseWebhook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UpdateWebhookResponseWebhookToJSON(value?: UpdateWebhookResponseWebhook | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

