/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateWebhookResponseWebhook } from './UpdateWebhookResponseWebhook';
import {
    UpdateWebhookResponseWebhookFromJSON,
    UpdateWebhookResponseWebhookFromJSONTyped,
    UpdateWebhookResponseWebhookToJSON,
} from './UpdateWebhookResponseWebhook';

/**
 * 
 * @export
 * @interface UpdateWebhookResponse
 */
export interface UpdateWebhookResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateWebhookResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWebhookResponse
     */
    code?: string;
    /**
     * 
     * @type {UpdateWebhookResponseWebhook}
     * @memberof UpdateWebhookResponse
     */
    webhook?: UpdateWebhookResponseWebhook;
}

/**
 * Check if a given object implements the UpdateWebhookResponse interface.
 */
export function instanceOfUpdateWebhookResponse(value: object): boolean {
    return true;
}

export function UpdateWebhookResponseFromJSON(json: any): UpdateWebhookResponse {
    return UpdateWebhookResponseFromJSONTyped(json, false);
}

export function UpdateWebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebhookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'webhook': json['webhook'] == null ? undefined : UpdateWebhookResponseWebhookFromJSON(json['webhook']),
    };
}

export function UpdateWebhookResponseToJSON(value?: UpdateWebhookResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'code': value['code'],
        'webhook': UpdateWebhookResponseWebhookToJSON(value['webhook']),
    };
}

