/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRolePermissionsResponse
 */
export interface UpdateRolePermissionsResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateRolePermissionsResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRolePermissionsResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateRolePermissionsResponse
     */
    permissionsAdded?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateRolePermissionsResponse
     */
    permissionsRemoved?: Array<string>;
}

/**
 * Check if a given object implements the UpdateRolePermissionsResponse interface.
 */
export function instanceOfUpdateRolePermissionsResponse(value: object): value is UpdateRolePermissionsResponse {
    return true;
}

export function UpdateRolePermissionsResponseFromJSON(json: any): UpdateRolePermissionsResponse {
    return UpdateRolePermissionsResponseFromJSONTyped(json, false);
}

export function UpdateRolePermissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRolePermissionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'permissionsAdded': json['permissions_added'] == null ? undefined : json['permissions_added'],
        'permissionsRemoved': json['permissions_removed'] == null ? undefined : json['permissions_removed'],
    };
}

  export function UpdateRolePermissionsResponseToJSON(json: any): UpdateRolePermissionsResponse {
      return UpdateRolePermissionsResponseToJSONTyped(json, false);
  }

  export function UpdateRolePermissionsResponseToJSONTyped(value?: UpdateRolePermissionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'permissions_added': value['permissionsAdded'],
        'permissions_removed': value['permissionsRemoved'],
    };
}

