/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateOrganizationUsersRequestUsersInner } from './UpdateOrganizationUsersRequestUsersInner';
import {
    UpdateOrganizationUsersRequestUsersInnerFromJSON,
    UpdateOrganizationUsersRequestUsersInnerFromJSONTyped,
    UpdateOrganizationUsersRequestUsersInnerToJSON,
    UpdateOrganizationUsersRequestUsersInnerToJSONTyped,
} from './UpdateOrganizationUsersRequestUsersInner';

/**
 * 
 * @export
 * @interface UpdateOrganizationUsersRequest
 */
export interface UpdateOrganizationUsersRequest {
    /**
     * Users to add, update or remove from the organization.
     * @type {Array<UpdateOrganizationUsersRequestUsersInner>}
     * @memberof UpdateOrganizationUsersRequest
     */
    users?: Array<UpdateOrganizationUsersRequestUsersInner>;
}

/**
 * Check if a given object implements the UpdateOrganizationUsersRequest interface.
 */
export function instanceOfUpdateOrganizationUsersRequest(value: object): value is UpdateOrganizationUsersRequest {
    return true;
}

export function UpdateOrganizationUsersRequestFromJSON(json: any): UpdateOrganizationUsersRequest {
    return UpdateOrganizationUsersRequestFromJSONTyped(json, false);
}

export function UpdateOrganizationUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationUsersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UpdateOrganizationUsersRequestUsersInnerFromJSON)),
    };
}

  export function UpdateOrganizationUsersRequestToJSON(json: any): UpdateOrganizationUsersRequest {
      return UpdateOrganizationUsersRequestToJSONTyped(json, false);
  }

  export function UpdateOrganizationUsersRequestToJSONTyped(value?: UpdateOrganizationUsersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UpdateOrganizationUsersRequestUsersInnerToJSON)),
    };
}

