/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBusinessRequest
 */
export interface UpdateBusinessRequest {
    /**
     * The name of the business.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    businessName?: string | null;
    /**
     * The email address of the business.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    email?: string | null;
    /**
     * The key of the industry of your business. Can be retrieved from the /industries endpoint.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    industryKey?: string | null;
    /**
     * Whether the business is using clickwrap agreements.
     * @type {boolean}
     * @memberof UpdateBusinessRequest
     */
    isClickWrap?: boolean | null;
    /**
     * Whether the business is showing Kinde branding. Requires a paid plan.
     * @type {boolean}
     * @memberof UpdateBusinessRequest
     */
    isShowKindeBranding?: boolean | null;
    /**
     * The Kinde perk code for the business.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    kindePerkCode?: string | null;
    /**
     * The phone number of the business.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    phone?: string | null;
    /**
     * The URL to the business's privacy policy.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    privacyUrl?: string | null;
    /**
     * The URL to the business's terms of service.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    termsUrl?: string | null;
    /**
     * The key of the timezone of your business. Can be retrieved from the /timezones endpoint.
     * @type {string}
     * @memberof UpdateBusinessRequest
     */
    timezoneKey?: string | null;
}

/**
 * Check if a given object implements the UpdateBusinessRequest interface.
 */
export function instanceOfUpdateBusinessRequest(value: object): value is UpdateBusinessRequest {
    return true;
}

export function UpdateBusinessRequestFromJSON(json: any): UpdateBusinessRequest {
    return UpdateBusinessRequestFromJSONTyped(json, false);
}

export function UpdateBusinessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBusinessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'businessName': json['business_name'] == null ? undefined : json['business_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'industryKey': json['industry_key'] == null ? undefined : json['industry_key'],
        'isClickWrap': json['is_click_wrap'] == null ? undefined : json['is_click_wrap'],
        'isShowKindeBranding': json['is_show_kinde_branding'] == null ? undefined : json['is_show_kinde_branding'],
        'kindePerkCode': json['kinde_perk_code'] == null ? undefined : json['kinde_perk_code'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'privacyUrl': json['privacy_url'] == null ? undefined : json['privacy_url'],
        'termsUrl': json['terms_url'] == null ? undefined : json['terms_url'],
        'timezoneKey': json['timezone_key'] == null ? undefined : json['timezone_key'],
    };
}

  export function UpdateBusinessRequestToJSON(json: any): UpdateBusinessRequest {
      return UpdateBusinessRequestToJSONTyped(json, false);
  }

  export function UpdateBusinessRequestToJSONTyped(value?: UpdateBusinessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'business_name': value['businessName'],
        'email': value['email'],
        'industry_key': value['industryKey'],
        'is_click_wrap': value['isClickWrap'],
        'is_show_kinde_branding': value['isShowKindeBranding'],
        'kinde_perk_code': value['kindePerkCode'],
        'phone': value['phone'],
        'privacy_url': value['privacyUrl'],
        'terms_url': value['termsUrl'],
        'timezone_key': value['timezoneKey'],
    };
}

