/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWebHookRequest
 */
export interface UpdateWebHookRequest {
    /**
     * Array of event type keys
     * @type {Array<string>}
     * @memberof UpdateWebHookRequest
     */
    eventTypes?: Array<string>;
    /**
     * The webhook name
     * @type {string}
     * @memberof UpdateWebHookRequest
     */
    name?: string;
    /**
     * The webhook description
     * @type {string}
     * @memberof UpdateWebHookRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateWebHookRequest interface.
 */
export function instanceOfUpdateWebHookRequest(value: object): value is UpdateWebHookRequest {
    return true;
}

export function UpdateWebHookRequestFromJSON(json: any): UpdateWebHookRequest {
    return UpdateWebHookRequestFromJSONTyped(json, false);
}

export function UpdateWebHookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebHookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'eventTypes': json['event_types'] == null ? undefined : json['event_types'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateWebHookRequestToJSON(value?: UpdateWebHookRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'event_types': value['eventTypes'],
        'name': value['name'],
        'description': value['description'],
    };
}

