/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateConnectionRequest
 */
export interface UpdateConnectionRequest {
    /**
     * The internal name of the connection.
     * @type {string}
     * @memberof UpdateConnectionRequest
     */
    name?: string;
    /**
     * The public facing name of the connection.
     * @type {string}
     * @memberof UpdateConnectionRequest
     */
    displayName?: string;
    /**
     * Client IDs of applications in which this connection is to be enabled.
     * @type {Array<string>}
     * @memberof UpdateConnectionRequest
     */
    enabledApplications?: Array<string>;
    /**
     * The connection's options (varies by strategy).
     * @type {object}
     * @memberof UpdateConnectionRequest
     */
    options?: object;
}

/**
 * Check if a given object implements the UpdateConnectionRequest interface.
 */
export function instanceOfUpdateConnectionRequest(value: object): value is UpdateConnectionRequest {
    return true;
}

export function UpdateConnectionRequestFromJSON(json: any): UpdateConnectionRequest {
    return UpdateConnectionRequestFromJSONTyped(json, false);
}

export function UpdateConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'enabledApplications': json['enabled_applications'] == null ? undefined : json['enabled_applications'],
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function UpdateConnectionRequestToJSON(value?: UpdateConnectionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'display_name': value['displayName'],
        'enabled_applications': value['enabledApplications'],
        'options': value['options'],
    };
}

