/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateIdentityRequest
 */
export interface UpdateIdentityRequest {
    /**
     * Whether the identity is the primary for it's type
     * @type {boolean}
     * @memberof UpdateIdentityRequest
     */
    isPrimary?: boolean;
}

/**
 * Check if a given object implements the UpdateIdentityRequest interface.
 */
export function instanceOfUpdateIdentityRequest(value: object): value is UpdateIdentityRequest {
    return true;
}

export function UpdateIdentityRequestFromJSON(json: any): UpdateIdentityRequest {
    return UpdateIdentityRequestFromJSONTyped(json, false);
}

export function UpdateIdentityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIdentityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isPrimary': json['is_primary'] == null ? undefined : json['is_primary'],
    };
}

  export function UpdateIdentityRequestToJSON(json: any): UpdateIdentityRequest {
      return UpdateIdentityRequestToJSONTyped(json, false);
  }

  export function UpdateIdentityRequestToJSONTyped(value?: UpdateIdentityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_primary': value['isPrimary'],
    };
}

