/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrganizationRequest
 */
export interface UpdateOrganizationRequest {
    /**
     * The organization's name.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    name?: string;
    /**
     * The organization's ID.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    externalId?: string;
    /**
     * The organization's brand settings - background color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    backgroundColor?: string;
    /**
     * The organization's brand settings - button color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    buttonColor?: string;
    /**
     * The organization's brand settings - button text color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    buttonTextColor?: string;
    /**
     * The organization's brand settings - link color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    linkColor?: string;
    /**
     * The organization's brand settings - dark mode background color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    backgroundColorDark?: string;
    /**
     * The organization's brand settings - dark mode button color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    buttonColorDark?: string;
    /**
     * The organization's brand settings - dark mode button text color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    buttonTextColorDark?: string;
    /**
     * The organization's brand settings - dark mode link color.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    linkColorDark?: string;
    /**
     * The organization's brand settings - theme/mode 'light' | 'dark' | 'user_preference'.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    themeCode?: string;
    /**
     * The organization's handle.
     * @type {string}
     * @memberof UpdateOrganizationRequest
     */
    handle?: string;
    /**
     * Users can sign up to this organization.
     * @type {boolean}
     * @memberof UpdateOrganizationRequest
     */
    isAllowRegistrations?: boolean;
}

/**
 * Check if a given object implements the UpdateOrganizationRequest interface.
 */
export function instanceOfUpdateOrganizationRequest(value: object): boolean {
    return true;
}

export function UpdateOrganizationRequestFromJSON(json: any): UpdateOrganizationRequest {
    return UpdateOrganizationRequestFromJSONTyped(json, false);
}

export function UpdateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'backgroundColor': json['background_color'] == null ? undefined : json['background_color'],
        'buttonColor': json['button_color'] == null ? undefined : json['button_color'],
        'buttonTextColor': json['button_text_color'] == null ? undefined : json['button_text_color'],
        'linkColor': json['link_color'] == null ? undefined : json['link_color'],
        'backgroundColorDark': json['background_color_dark'] == null ? undefined : json['background_color_dark'],
        'buttonColorDark': json['button_color_dark'] == null ? undefined : json['button_color_dark'],
        'buttonTextColorDark': json['button_text_color_dark'] == null ? undefined : json['button_text_color_dark'],
        'linkColorDark': json['link_color_dark'] == null ? undefined : json['link_color_dark'],
        'themeCode': json['theme_code'] == null ? undefined : json['theme_code'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'isAllowRegistrations': json['is_allow_registrations'] == null ? undefined : json['is_allow_registrations'],
    };
}

export function UpdateOrganizationRequestToJSON(value?: UpdateOrganizationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'external_id': value['externalId'],
        'background_color': value['backgroundColor'],
        'button_color': value['buttonColor'],
        'button_text_color': value['buttonTextColor'],
        'link_color': value['linkColor'],
        'background_color_dark': value['backgroundColorDark'],
        'button_color_dark': value['buttonColorDark'],
        'button_text_color_dark': value['buttonTextColorDark'],
        'link_color_dark': value['linkColorDark'],
        'theme_code': value['themeCode'],
        'handle': value['handle'],
        'is_allow_registrations': value['isAllowRegistrations'],
    };
}

