/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRolePermissionsRequestPermissionsInner
 */
export interface UpdateRolePermissionsRequestPermissionsInner {
    /**
     * The permission id.
     * @type {string}
     * @memberof UpdateRolePermissionsRequestPermissionsInner
     */
    id?: string;
    /**
     * Optional operation, set to 'delete' to remove the permission from the role.
     * @type {string}
     * @memberof UpdateRolePermissionsRequestPermissionsInner
     */
    operation?: string;
}

/**
 * Check if a given object implements the UpdateRolePermissionsRequestPermissionsInner interface.
 */
export function instanceOfUpdateRolePermissionsRequestPermissionsInner(value: object): value is UpdateRolePermissionsRequestPermissionsInner {
    return true;
}

export function UpdateRolePermissionsRequestPermissionsInnerFromJSON(json: any): UpdateRolePermissionsRequestPermissionsInner {
    return UpdateRolePermissionsRequestPermissionsInnerFromJSONTyped(json, false);
}

export function UpdateRolePermissionsRequestPermissionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRolePermissionsRequestPermissionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'operation': json['operation'] == null ? undefined : json['operation'],
    };
}

  export function UpdateRolePermissionsRequestPermissionsInnerToJSON(json: any): UpdateRolePermissionsRequestPermissionsInner {
      return UpdateRolePermissionsRequestPermissionsInnerToJSONTyped(json, false);
  }

  export function UpdateRolePermissionsRequestPermissionsInnerToJSONTyped(value?: UpdateRolePermissionsRequestPermissionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'operation': value['operation'],
    };
}

