/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserIdentityResult } from './UserIdentityResult';
import {
    UserIdentityResultFromJSON,
    UserIdentityResultFromJSONTyped,
    UserIdentityResultToJSON,
    UserIdentityResultToJSONTyped,
} from './UserIdentityResult';

/**
 * 
 * @export
 * @interface UserIdentity
 */
export interface UserIdentity {
    /**
     * The type of identity object created.
     * @type {string}
     * @memberof UserIdentity
     */
    type?: string;
    /**
     * 
     * @type {UserIdentityResult}
     * @memberof UserIdentity
     */
    result?: UserIdentityResult;
}

/**
 * Check if a given object implements the UserIdentity interface.
 */
export function instanceOfUserIdentity(value: object): value is UserIdentity {
    return true;
}

export function UserIdentityFromJSON(json: any): UserIdentity {
    return UserIdentityFromJSONTyped(json, false);
}

export function UserIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdentity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'result': json['result'] == null ? undefined : UserIdentityResultFromJSON(json['result']),
    };
}

  export function UserIdentityToJSON(json: any): UserIdentity {
      return UserIdentityToJSONTyped(json, false);
  }

  export function UserIdentityToJSONTyped(value?: UserIdentity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'result': UserIdentityResultToJSON(value['result']),
    };
}

