/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The result of the user creation operation.
 * @export
 * @interface UserIdentityResult
 */
export interface UserIdentityResult {
    /**
     * True if the user identity was successfully created.
     * @type {boolean}
     * @memberof UserIdentityResult
     */
    created?: boolean;
}

/**
 * Check if a given object implements the UserIdentityResult interface.
 */
export function instanceOfUserIdentityResult(value: object): value is UserIdentityResult {
    return true;
}

export function UserIdentityResultFromJSON(json: any): UserIdentityResult {
    return UserIdentityResultFromJSONTyped(json, false);
}

export function UserIdentityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdentityResult {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
    };
}

  export function UserIdentityResultToJSON(json: any): UserIdentityResult {
      return UserIdentityResultToJSONTyped(json, false);
  }

  export function UserIdentityResultToJSONTyped(value?: UserIdentityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
    };
}

