/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Webhook
 */
export interface Webhook {
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    endpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Webhook
     */
    eventTypes?: Array<string>;
    /**
     * Created on date in ISO 8601 format.
     * @type {string}
     * @memberof Webhook
     */
    createdOn?: string;
}

/**
 * Check if a given object implements the Webhook interface.
 */
export function instanceOfWebhook(value: object): boolean {
    return true;
}

export function WebhookFromJSON(json: any): Webhook {
    return WebhookFromJSONTyped(json, false);
}

export function WebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webhook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'description': json['description'] == null ? undefined : json['description'],
        'eventTypes': json['event_types'] == null ? undefined : json['event_types'],
        'createdOn': json['created_on'] == null ? undefined : json['created_on'],
    };
}

export function WebhookToJSON(value?: Webhook | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'endpoint': value['endpoint'],
        'description': value['description'],
        'event_types': value['eventTypes'],
        'created_on': value['createdOn'],
    };
}

