name: Update Code

on:
  push:
    paths:
      - kinde-mgmt-api-specs.yaml
    branches:
      - main
  workflow_dispatch:

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Generate SDK
        run: pnpm -C sdk i && ./generate.sh
      - name: Commit and push if changed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            # Configure the github actions bot user
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"

            # Commit and push the changes
            git add sdk
            git commit -m "chore: update sdk"
            npm version minor
            git push

            gh workflow run 3-update-package.yaml
          fi
