name: Update Code

on:
  push:
    paths:
      - kinde-mgmt-api-specs.yaml
    branches:
      - main
  workflow_dispatch:

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Set up git
        run: |
          # Configure the github actions bot user
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: Generate, build and push
        working-directory: sdk
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pnpm i
          mkdir -p ./.git # trick npm into running git commit and git tag while versioning
          npm version minor
          rmdir ./.git
          gh workflow run 3-update-package.yaml
