name: Update Package

on:
  push:
    paths:
      - "sdk/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc && npm --prefix sdk publish
