name: Update Package

on:
  push:
    paths:
      - "sdk/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to npm
        run: npm publish sdk
